name: force_upgrader
description: Flutter package to force users to upgrade past a minimum version.
version: 0.0.1
homepage: https://github.com/sethmicahking/force_upgrader

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^1.4.2
  url_launcher: ^6.1.2
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
