name: force_upgrader
description: Flutter package to force users to upgrade past a minimum version.
version: 0.0.1
homepage: https://github.com/sethmicahking/force_upgrader

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # You can use the PackageInfo to query information about the application package.
  package_info_plus: ^1.4.2

  # A Flutter plugin for launching a URL.
  url_launcher: ^6.1.2

  # A dart library providing a Version object for comparing and incrementing version numbers in compliance with the Semantic Versioning spec at http://semver.org/
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
